### ISSUE TITLE
Searchterm (field: subject) doesn't work, cause it's never set

### ISSUE THREAD

**Issue by wimbschimmelpfennig** [georgringer/news_filter#13]
I followed the guide for this extension, and couldn't get the search for text to work.

Only after I added the following lines:

List.html:
`<f:form.hidden property="fields" value="teaser,title,bodytext" />`

EnrichDemandObject.php (after line 33):
`$demand->setSearch($search);`

Am I overlooking something?

I digged a little and I think this feature went missing when changing from Signalslot to the new Hook, the field "subject" arrives in EnrichDemandObject.php, but never gets used in any way. The line I added to the hook fixes the problem, but overwrites predfined settings like the search fields, which I added back via the hidden field.

**Comment by klodeckl** [comment]
Thanks @wimbschimmelpfennig, works also for me.

**Comment by kitzberger** [comment]
It'll be fixed in the 11/12 compatible version of this extension.
