### ISSUE TITLE
Implement ordering of categories

### ISSUE THREAD

**Issue by klodeckl** [georgringer/news_filter#16]
Helllo,

I found the code for the ordering in the category Repository, but it seems ordering does not get into the repository. I hardcoded this to get my ordering:

        $query->setOrderings(
            [
                'sorting' => \TYPO3\CMS\Extbase\Persistence\QueryInterface::ORDER_ASCENDING,
                'title' => \TYPO3\CMS\Extbase\Persistence\QueryInterface::ORDER_ASCENDING
            ]
        );

Perfect solution would be to set ordering in the flexform. I will upload a PR when time allows it.

**Comment by cepheiVV** [comment]
The _flexform_ field `settings.filterCategories` currently loads TYPO3 `pages` where the categories are stored.
However, it would make more sense to load `sys_catgory` records in this settings field instead of `pages` records.
With this change, we could also allow for category sortings.

**Comment by kitzberger** [comment]
@cepheiVV, i'm not entirely sure, but this might be resolved by one of these PRs?

* https://github.com/georgringer/news_filter/pull/9
* https://github.com/georgringer/news_filter/pull/18

**Comment by kitzberger** [comment]
@klodeckl, feature is part of latest release [2.1.0](https://github.com/georgringer/news_filter/releases/tag/2.1.0)
